export const domExercises = [
  {
    header: "Schere, Stein, Papier",
    description: "Im HTML & CSS Modul hast du eine Rezeptseite aufgebaut, du kannst diese verwenden oder zur Übung eine neue Rezeptseite aufbauen. In diesem Projekt geht es zwar nicht in erster Linie um das Styling, dennoch kann eine kleine Auffrischung nicht schaden. Das Ziel dieser Aufgabe ist eine Rezeptseite aufzubauen, die mit dynamischen Daten gefüllt ist und auf Userinteraktionen reagiert.",
    tasks: [
      "PLANUNGSPHASE",
      "1. Plane dein Vorgehen grob",
      "2. Lege einen Branch mit deinem Namen an, pushe regelmäßig und erzeuge einen Pull Request",
      "3. Suche dir 5-10 Rezepte raus",
      "VORBEREITUNGEN",
      "1. Lege die rezeptDaten als Array of Objekts an",
      "2. Lege die userDaten als Array of Objekts an (userName, password und 1-3 Lieblingsrezepte)",
      "3. Daten sollten Ausgelagert werden (ES6 Modules) import/export",
      "CODING",
      "1. Gib alle Rezepte in Rezeptkarten aus",
      "2. Baue ein Login Formular auf",
      "3. Style die Rezeptkarten und das Formular",
      "4. Werte die Login-Daten (userName und password) aus",
      "5. Wenn der User sich eingeloggt hat, gebe seinen userName auf der Seite aus",
      "6. Klickt der User auf Logout, soll er ausgeloggt werden. Ein erneuter Login sollte weiterhin möglich sein",
      "7. Ist der user eingeloggt sollten seine Lieblingsrezepte angezeigt werden",
      "BONUS",
      "1. Der eingeloggte User sollte weitere Rezepte zu seinen Favoriten hinzufügen können",
    ],
    commands: "Benötigte Skills: HTML, CSS, Map/Filter, Umgang mit Arrays of Objekten, querySelector, innerHTML, Events",
    img: "",
    time: 2,
    url: "https://github.com/MartinKruess/domExercise.git",
    download: "",
    type: "dom",
  },
];
