export const arrayMethods = [
  {
    command: 'users.length',
    description: 'Gibt die Länge des Arrays wieder und wird oft verwendet um die Adresse [x] herauszufinden (.length -1)',
    urlName: 'LENGTH',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length',
  },
  {
    command: 'users.push("Mr.Hammer", "BurgerFan03")',
    description: 'Fügt ein oder mehr Elemente am Ende des Arrays ein',
    urlName: 'PUSH',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push',
  },
  {
    command: 'user.pop()',
    description: 'Löscht das letzte Element eines Arrays (nur einzelnd ausführbar!)',
    urlName: 'POP',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop',
  },
  {
    command: 'users.filter()',
    description: 'Filtert ein Array nach den Suchkriterien und erzeugt daraus ein neues Array.',
    urlName: 'FILTER',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter',
  },
  {
    command: 'users.find() / findIndex()',
    description: 'Durchsucht das Array nach einem passenden Element. Die Ausgabe je nach Variante find = Element, findIndex = index. ACHTUNG: Nur der erste gefunden Wert wird zurückgegeben. Es wird nach einem Fund das Array NICHT weiter durchsucht.',
    urlName: 'FIND',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find',
  },
  {
    command: 'user.map()',
    description: 'Erzeugt ein neues Array und führt gewünschte Veränderungen an jedem Element durch ohne das original Array zu verändern. Ist die Standard-Ausgabe Methode in React!',
    urlName: 'MAP',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Map',
  },
  {
    command: 'user.sort()',
    description: 'Sortiert das original Array nach den angegebenen Parametern',
    urlName: 'SORT',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort',
  },
  {
    command: 'user.reduce()',
    description: 'Gibt die Summe aller Elemente als Array zurück.',
    urlName: 'REDUCE',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce',
  },
  {
    command: 'user.forEach()',
    description: 'Führt eine Funktion für jedes Element einmal aus. Im gegensatz zu Map ist forEach nicht Verknüpfbar.',
    urlName: 'FOR EACH',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach',
  },
  {
    command: 'user.unshift("BurgerFan04", "SiegbertDerStarke")',
    description: 'Fügt ein oder mehr Elemente am Anfang eines Arrays ein und verschiebt alle Vorhandenen Elemente. ACHTUNG: Wenn feste Positionen im Code angegben sind, werden diese verschoben!',
    urlName: 'UNSHIFT',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift',
  },
  {
    command: 'user.shift()',
    description: 'Entfernt das erste Element aus einem Array. ACHTUNG: Auch hierbei verschieben sich alle Element-Adressen',
    urlName: 'SHIFT',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift',
  },
  {
    command: 'user.concat()',
    description: 'Erzeugt ein neues Array aus zwei oder mehr Arrays',
    urlName: 'CONCAT',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat',
  },
  {
    command: 'user.slice(-3)',
    description: 'Erzeugt ein neues Arrays aus einem Teilbereich des Ursprungsarrays ohne das original Array zu verändern.',
    urlName: 'LENGTH',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice',
  },
  {
    command: 'user.splice(2, 0, "Albertino")',
    description: 'Lässt sich auf verschiedene Arten anwenden. ACHTUNG: Das original Array wird hierbei verändert!',
    urlName: 'LENGTH',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice',
  },
  {
    command: 'user.reverse()',
    description: 'Gibt das Array von hinten nach vorne aus',
    urlName: 'REVERSE',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse',
  },
  {
    command: 'user.join("-")',
    description: 'Fügt eine Zeichenkette an oder entfernt diese bei jedem Element.',
    urlName: 'JOIN',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join',
  },
  {
    command: 'user.includes()',
    description: 'Überprüft ob ein Element einen Wert oder Teilwert enthält. Return: ture/false',
    urlName: 'INCLUDES',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes',
  },
]